# Generated by Django 2.1.3 on 2018-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdmovie', '0003_auto_20181125_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='audio',
            field=models.ManyToManyField(blank=True, related_name='audio', to='dvdmovie.Language'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='subtitle',
            field=models.ManyToManyField(blank=True, related_name='subs', to='dvdmovie.Language'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='director', to='dvdmovie.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='dvdmovie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='star', through='dvdmovie.Star', to='dvdmovie.Person'),
        ),
        migrations.AlterField(
            model_name='partofseries',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='nameknownby',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='series',
            name='movies',
            field=models.ManyToManyField(blank=True, through='dvdmovie.PartOfSeries', to='dvdmovie.Movie'),
        ),
    ]
