# Generated by Django 2.1.3 on 2018-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdmovie', '0006_auto_20181202_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofseries',
            name='number',
            field=models.FloatField(null=True),
        ),
    ]
