# Generated by Django 2.1.3 on 2018-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdmovie', '0008_auto_20181202_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofseries',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='Number Order'),
        ),
    ]
