# Generated by Django 2.1.3 on 2018-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdmovie', '0009_auto_20181202_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Is Director'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_star',
            field=models.BooleanField(default=False, verbose_name='Is Actor'),
        ),
    ]
